---

- hosts: all
  become: true
  tasks:

  - name: Update packages for Ubuntu-based distros
    package:
      update_cache: yes

  - name: Copy a file to home directory
    copy:
      src: test.txt
      dest: /home/ledlong/
      owner: ledlong
      mode: 0644
