---

- hosts: all
  become: true
  tasks:

  - name: Install apache2 and related packages for Ubuntu-based distros
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Install httpd and related packages for CentOS-based distros
    yum:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"
