---

- hosts: all
  become: true
  tasks:

  - name: Update packages
    package:
      update_cache: yes

      #  - name: Install apache2 for Ubuntu-based servers
      #apt:
      #name: apache2
      #state: latest
      #when: ansible_distribution == "Ubuntu"

      #  - name: Install httpd for CentOS-based servers
      #yum:
      #name: httpd
      #state: latest
      #when: ansible_distribution == "CentOS"

  - name: Start httpd for CentOS-based servers
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentOS"

